version: "3.7" 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/mnt/e/xampp/htdocs/Projet:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mysql
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - "/mnt/e/xampp/htdocs/Projet:/var/www/html/"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
      # - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
volumes:
  mysql: